### ISSUE TITLE
Cannot connect to Acestream engine! python3.6/site-packages/acestream/engine.py

### ISSUE THREAD

**Issue by buriedaliveIX** [jonian/acestream-launcher#42]
misery@srv02 ~/.local/bin $ ./acestream-launcher acestream://5d05292814f6768e6635c17475336d88d4fff9a6 --player mpv
Connecting to Acestream engine.../bin/sh: warning: shell level (1000) too high, resetting to 1
/bin/sh: warning: shell level (1000) too high, resetting to 1
Cannot connect to Acestream engine!

Exiting...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/misery/.local/lib64/python3.6/site-packages/acestream/engine.py", line 53, in _start_process
    self.process.communicate()
AttributeError: 'NoneType' object has no attribute 'communicate'

**Comment by buriedaliveIX** [comment]
this issue after change python 3_6 to 3_7
I include 3_6 for all needed packages, but not have positive results
Need help,
misery@srv02 ~ $ uname -a
Linux srv02 5.4.28-gentoo-x86_64 #1 SMP Tue Apr 14 04:20:34 +07 2020 x86_64 AMD E-450 APU with Radeon(tm) HD Graphics AuthenticAMD GNU/Linux

**Comment by buriedaliveIX** [comment]
after full update
misery@srv02 ~/.local/bin $ ./acestream-launcher acestream://5d05292814f6768e6635c17475336d88d4fff9a6 --player mpv
Connecting to Acestream engine.../bin/sh: warning: shell level (1000) too high, resetting to 1
Cannot connect to Acestream engine!

Exiting...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/misery/.local/lib/python3.7/site-packages/acestream/engine.py", line 52, in _start_process
    self.emit('started')
  File "/home/misery/.local/lib/python3.7/site-packages/acestream/object.py", line 21, in emit
    event['callback_fn'](*callback_args)
  File "/home/misery/.local/lib/python3.7/site-packages/acestream_launcher/stream.py", line 69, in _on_engine_started
    self._start_stream()
  File "/home/misery/.local/lib/python3.7/site-packages/acestream_launcher/stream.py", line 48, in _start_stream
    self.stream.start()
  File "/home/misery/.local/lib/python3.7/site-packages/acestream/stream.py", line 71, in start
    response = self.server.getstream(pid=self.pid, hls=hls, **kwparams)
  File "/home/misery/.local/lib/python3.7/site-packages/acestream/server.py", line 114, in getstream
    if LooseVersion(self.version) < LooseVersion('3.1.29'):
  File "/usr/lib/python3.7/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/usr/lib/python3.7/distutils/version.py", line 335, in _cmp
    if self.version == other.version:
AttributeError: 'LooseVersion' object has no attribute 'version'
