### ISSUE TITLE
Execution results in error: AttributeError: 'LooseVersion' object has no attribute 'version'

### ISSUE THREAD

**Issue by apqlzm** [jonian/acestream-launcher#43]
This is a minor issue but you may want to know that it happens.
Executing launcher while providing `acestreamengine` value for optional argument `--engine` results in exception.

Example:
`acestream-launcher acestream://2aae6c35c94fcfb415dbe95f408b9ce91ee846ed --engine acestreamengine`

Output:
```
Cannot connect to Acestream engine!

Exiting...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.9/site-packages/acestream/engine.py", line 52, in _start_process
    self.emit('started')
  File "/usr/lib/python3.9/site-packages/acestream/object.py", line 21, in emit
    event['callback_fn'](*callback_args)
  File "/usr/lib/python3.9/site-packages/acestream_launcher/stream.py", line 84, in _on_engine_started
    self._start_stream()
  File "/usr/lib/python3.9/site-packages/acestream_launcher/stream.py", line 50, in _start_stream
    self.stream.start()
  File "/usr/lib/python3.9/site-packages/acestream/stream.py", line 71, in start
    response = self.server.getstream(pid=self.pid, hls=hls, **kwparams)
  File "/usr/lib/python3.9/site-packages/acestream/server.py", line 116, in getstream
    if LooseVersion(self.version) < LooseVersion('3.1.29'):
  File "/usr/lib/python3.9/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/usr/lib/python3.9/distutils/version.py", line 339, in _cmp
    if self.version == other.version:
AttributeError: 'LooseVersion' object has no attribute 'version
```

Tested on Manjaro distribution
acestream-launcher version 2.0.3-1
acestreamengine version version: 3.1.49 revision: dc5eac3

Thank you for your great work

**Comment by jonian** [comment]
Hi @apqlzm, thanks for the report. How did you install acestream-launcher and acestreamengine? If you installed them from AUR, which packages?

**Comment by apqlzm** [comment]
Example comes from AUR installed packages.

acestream-launcher
pkgver=2.0.3

acestream-engine
pkgver=3.1.49

**Comment by jonian** [comment]
Acestream engine can't work without a client parameter. check `acestreamengine --help` for available clients. you should change your command to:

```sh
 acestream-launcher acestream://2aae6c35c94fcfb415dbe95f408b9ce91ee846ed --engine 'acestreamengine --client-console'
```
