### ISSUE TITLE
Stopped working since DE change.

### ISSUE THREAD

**Issue by kuttarunge** [jonian/acestream-launcher#8]
Using Arch, changed from gnome to xfce and now I am getting this problem:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.Notifications': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/acestream-launcher", line 161, in <module>
    main()
  File "/usr/bin/acestream-launcher", line 151, in main
    AcestreamLauncher()
  File "/usr/bin/acestream-launcher", line 41, in __init__
    notify2.init(self.appname)
  File "/usr/lib/python3.6/site-packages/notify2.py", line 103, in init
    '/org/freedesktop/Notifications')
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.Notifications exited with status 127.

**Comment by andrestoga** [comment]
I'm having the following error in Ubuntu 14.04:

Traceback (most recent call last):
  File "/usr/bin/acestream-launcher", line 161, in <module>
    main()
  File "/usr/bin/acestream-launcher", line 151, in main
    AcestreamLauncher()
  File "/usr/bin/acestream-launcher", line 44, in __init__
    self.start_acestream()
  File "/usr/bin/acestream-launcher", line 70, in start_acestream
    if 'acestreamengine' in process.name():
TypeError: 'str' object is not callable

**Comment by jonian** [comment]
@kuttarunge this must be fixed in version 1.0.0.
@andrestoga try version 1.0.0. It should be fixed. If not, open a new issue.
